# Generated by Django 4.2.27 on 2026-01-30 04:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(max_length=2, verbose_name='tipo de comprobante')),
                ('establecimiento', models.CharField(max_length=3, verbose_name='establecimiento')),
                ('punto_emision', models.CharField(max_length=3, verbose_name='punto de emisión')),
                ('secuencial', models.CharField(max_length=9, verbose_name='secuencial')),
                ('numero_comprobante', models.CharField(max_length=17, verbose_name='número de comprobante')),
                ('clave_acceso', models.CharField(blank=True, max_length=49, null=True, unique=True, verbose_name='clave de acceso')),
                ('fecha_emision', models.DateTimeField(verbose_name='fecha de emisión')),
                ('xml_generado', models.TextField(blank=True, verbose_name='XML generado')),
                ('xml_firmado', models.TextField(blank=True, verbose_name='XML firmado')),
                ('pdf_ride', models.FileField(blank=True, null=True, upload_to='ride/', verbose_name='PDF RIDE')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('ENVIADO', 'Enviado al SRI'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('NO_AUTORIZADO', 'No Autorizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, verbose_name='número de autorización')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de autorización')),
                ('respuesta_sri', models.JSONField(blank=True, null=True, verbose_name='respuesta del SRI')),
                ('mensajes_sri', models.TextField(blank=True, verbose_name='mensajes del SRI')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'comprobante electrónico',
                'verbose_name_plural': 'comprobantes electrónicos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Secuencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('04', 'Nota de Crédito'), ('05', 'Nota de Débito'), ('06', 'Guía de Remisión'), ('07', 'Comprobante de Retención')], max_length=2, verbose_name='tipo de comprobante')),
                ('establecimiento', models.CharField(max_length=3, verbose_name='establecimiento')),
                ('punto_emision', models.CharField(max_length=3, verbose_name='punto de emisión')),
                ('secuencial_actual', models.IntegerField(default=0, verbose_name='secuencial actual')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuenciales', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'secuencial',
                'verbose_name_plural': 'secuenciales',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='subtotal sin impuestos')),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal 0%')),
                ('subtotal_12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal 12%')),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal 15%')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total descuento')),
                ('iva_12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA 12%')),
                ('iva_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA 15%')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('informacion_adicional', models.JSONField(blank=True, null=True, verbose_name='información adicional')),
                ('forma_pago', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos')], default='20', max_length=20, verbose_name='forma de pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente', verbose_name='cliente')),
                ('comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='facturacion.comprobanteelectronico', verbose_name='comprobante')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ['-comprobante__fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_principal', models.CharField(max_length=25, verbose_name='código principal')),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=25, verbose_name='código auxiliar')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='descuento')),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio total sin impuesto')),
                ('codigo_impuesto', models.CharField(choices=[('2', 'IVA'), ('3', 'ICE')], default='2', max_length=1, verbose_name='código impuesto')),
                ('codigo_porcentaje', models.CharField(choices=[('0', '0%'), ('2', '12%'), ('3', '14%'), ('4', '15%'), ('6', 'No Objeto de Impuesto'), ('7', 'Exento de IVA')], default='2', max_length=2, verbose_name='código porcentaje')),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tarifa')),
                ('valor_impuesto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor impuesto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura', verbose_name='factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'detalle de factura',
                'verbose_name_plural': 'detalles de factura',
                'ordering': ['id'],
            },
        ),
    ]
