# Generated by Django 4.2.27 on 2026-01-30 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='usuario creador'),
        ),
        migrations.AlterUniqueTogether(
            name='secuencial',
            unique_together={('empresa', 'tipo_comprobante', 'establecimiento', 'punto_emision')},
        ),
        migrations.AddIndex(
            model_name='comprobanteelectronico',
            index=models.Index(fields=['empresa', 'estado'], name='facturacion_empresa_8a09ab_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobanteelectronico',
            index=models.Index(fields=['clave_acceso'], name='facturacion_clave_a_28fbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobanteelectronico',
            index=models.Index(fields=['numero_comprobante'], name='facturacion_numero__aa531a_idx'),
        ),
    ]
