# Generated by Django 4.2.27 on 2026-03-06 06:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=300, verbose_name="motivo")),
                (
                    "subtotal_sin_impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal sin impuestos",
                    ),
                ),
                (
                    "total_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total descuento",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor de modificación",
                    ),
                ),
                (
                    "comprobante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota_credito",
                        to="facturacion.comprobanteelectronico",
                        verbose_name="comprobante",
                    ),
                ),
                (
                    "factura_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_credito",
                        to="facturacion.factura",
                        verbose_name="factura de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota de crédito",
                "verbose_name_plural": "notas de crédito",
                "ordering": ["-comprobante__fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="DetalleNotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_principal",
                    models.CharField(max_length=25, verbose_name="código principal"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=300, verbose_name="descripción"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="precio unitario"
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="descuento",
                    ),
                ),
                (
                    "precio_total_sin_impuesto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="precio total sin impuesto",
                    ),
                ),
                (
                    "codigo_impuesto",
                    models.CharField(
                        default="2", max_length=1, verbose_name="código impuesto"
                    ),
                ),
                (
                    "codigo_porcentaje",
                    models.CharField(
                        default="2", max_length=2, verbose_name="código porcentaje"
                    ),
                ),
                (
                    "tarifa",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="tarifa"
                    ),
                ),
                (
                    "valor_impuesto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor impuesto"
                    ),
                ),
                (
                    "nota_credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="facturacion.notacredito",
                        verbose_name="nota de crédito",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle de nota de crédito",
                "verbose_name_plural": "detalles de nota de crédito",
                "ordering": ["id"],
            },
        ),
    ]
