# Generated by Django 4.2.27 on 2026-03-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("facturacion", "0003_nota_credito"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo_fiscal",
                    models.CharField(max_length=7, verbose_name="período fiscal"),
                ),
                (
                    "comprobante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retencion",
                        to="facturacion.comprobanteelectronico",
                        verbose_name="comprobante",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retenciones",
                        to="clientes.cliente",
                        verbose_name="proveedor / sujeto retenido",
                    ),
                ),
            ],
            options={
                "verbose_name": "retención",
                "verbose_name_plural": "retenciones",
                "ordering": ["-comprobante__fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="ImpuestoRetencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=1, verbose_name="código impuesto"),
                ),
                (
                    "codigo_porcentaje",
                    models.CharField(max_length=4, verbose_name="código porcentaje"),
                ),
                (
                    "tarifa",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="tarifa %"
                    ),
                ),
                (
                    "base_imponible",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="base imponible"
                    ),
                ),
                (
                    "valor_retenido",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor retenido"
                    ),
                ),
                (
                    "cod_doc_sustento",
                    models.CharField(
                        default="01", max_length=2, verbose_name="cod. doc. sustento"
                    ),
                ),
                (
                    "num_doc_sustento",
                    models.CharField(max_length=17, verbose_name="nro. doc. sustento"),
                ),
                (
                    "fecha_emision_doc_sustento",
                    models.DateField(verbose_name="fecha emisión doc. sustento"),
                ),
                (
                    "retencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impuestos",
                        to="facturacion.retencion",
                        verbose_name="retención",
                    ),
                ),
            ],
            options={
                "verbose_name": "impuesto de retención",
                "verbose_name_plural": "impuestos de retención",
                "ordering": ["id"],
            },
        ),
    ]
