# Generated by Django 4.2.27 on 2026-03-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_add_retencion_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinatarioGuia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacion_destinatario",
                    models.CharField(max_length=20, verbose_name="identificación"),
                ),
                (
                    "razon_social_destinatario",
                    models.CharField(max_length=300, verbose_name="razón social"),
                ),
                (
                    "dir_dest_destinatario",
                    models.CharField(max_length=300, verbose_name="dirección destino"),
                ),
                (
                    "motorista_y_ca",
                    models.CharField(
                        default="Venta", max_length=300, verbose_name="motivo traslado"
                    ),
                ),
                (
                    "ruta",
                    models.CharField(blank=True, max_length=300, verbose_name="ruta"),
                ),
                (
                    "cod_doc_sustento",
                    models.CharField(
                        default="01", max_length=2, verbose_name="cod. doc. sustento"
                    ),
                ),
                (
                    "num_doc_sustento",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="nro. doc. sustento"
                    ),
                ),
                (
                    "fecha_emision_doc_sust",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha emisión doc. sustento",
                    ),
                ),
                (
                    "num_autorizacion_doc_sust",
                    models.CharField(
                        blank=True,
                        max_length=49,
                        verbose_name="nro. autorización doc. sustento",
                    ),
                ),
            ],
            options={
                "verbose_name": "destinatario de guía",
                "verbose_name_plural": "destinatarios de guía",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GuiaRemision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc_transportista",
                    models.CharField(max_length=13, verbose_name="RUC transportista"),
                ),
                (
                    "razon_social_transportista",
                    models.CharField(
                        max_length=300, verbose_name="razón social transportista"
                    ),
                ),
                ("placa", models.CharField(max_length=20, verbose_name="placa")),
                (
                    "fecha_inicio_transporte",
                    models.DateField(verbose_name="fecha inicio transporte"),
                ),
                (
                    "fecha_fin_transporte",
                    models.DateField(verbose_name="fecha fin transporte"),
                ),
                (
                    "dir_partida",
                    models.CharField(
                        max_length=300, verbose_name="dirección de partida"
                    ),
                ),
                (
                    "comprobante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guia_remision",
                        to="facturacion.comprobanteelectronico",
                        verbose_name="comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "guía de remisión",
                "verbose_name_plural": "guías de remisión",
                "ordering": ["-comprobante__fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="DetalleGuiaRemision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_interno",
                    models.CharField(max_length=25, verbose_name="código interno"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=300, verbose_name="descripción"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="cantidad"
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="facturacion.destinatarioguia",
                        verbose_name="destinatario",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle de guía de remisión",
                "verbose_name_plural": "detalles de guía de remisión",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="destinatarioguia",
            name="guia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinatarios",
                to="facturacion.guiaremision",
                verbose_name="guía de remisión",
            ),
        ),
    ]
