# Generated by Django 4.2.27 on 2026-03-07 04:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("facturacion", "0005_add_guia_remision_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaDebito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=300, verbose_name="motivo")),
                (
                    "subtotal_sin_impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal sin impuestos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="total",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_debito",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "comprobante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nota_debito",
                        to="facturacion.comprobanteelectronico",
                        verbose_name="comprobante",
                    ),
                ),
                (
                    "factura_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_debito",
                        to="facturacion.factura",
                        verbose_name="factura de origen (opcional)",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota de débito",
                "verbose_name_plural": "notas de débito",
                "ordering": ["-comprobante__fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="DetalleNotaDebito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon", models.CharField(max_length=300, verbose_name="razón")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor",
                    ),
                ),
                (
                    "codigo_impuesto",
                    models.CharField(
                        default="2", max_length=1, verbose_name="código impuesto"
                    ),
                ),
                (
                    "codigo_porcentaje",
                    models.CharField(
                        default="4", max_length=2, verbose_name="código porcentaje"
                    ),
                ),
                (
                    "tarifa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="tarifa",
                    ),
                ),
                (
                    "valor_impuesto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="valor impuesto",
                    ),
                ),
                (
                    "nota_debito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="facturacion.notadebito",
                        verbose_name="nota de débito",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle de nota de débito",
                "verbose_name_plural": "detalles de nota de débito",
                "ordering": ["id"],
            },
        ),
    ]
