# Generated by Django 4.2.27 on 2026-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0006_add_nota_debito_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="secuencial",
            name="configurado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el secuencial inicial fue configurado manualmente. Una vez True, no se puede reducir el valor.",
                verbose_name="configurado",
            ),
        ),
    ]
