# Generated by Django 4.2.27 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_comprobante_contexto_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='procesamiento_en_curso',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
