# Generated by Django 4.2.27 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_comprobante_procesamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='procesamiento_iniciado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
