# Generated by Django 4.2.27 on 2026-01-30 04:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_principal', models.CharField(max_length=25, verbose_name='código principal')),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=25, verbose_name='código auxiliar')),
                ('tipo', models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio')], default='BIEN', max_length=10, verbose_name='tipo')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio')),
                ('precio_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Precio mínimo de venta', max_digits=12, null=True, verbose_name='precio mínimo')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='costo')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='aplica IVA')),
                ('porcentaje_iva', models.CharField(choices=[('0', '0%'), ('2', '12%'), ('4', '15%'), ('6', 'No Objeto de Impuesto'), ('7', 'Exento de IVA')], default='2', max_length=2, verbose_name='porcentaje IVA')),
                ('maneja_inventario', models.BooleanField(default=False, verbose_name='maneja inventario')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='stock mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['empresa', 'activo'], name='productos_p_empresa_264f06_idx'), models.Index(fields=['codigo_principal'], name='productos_p_codigo__1833cf_idx')],
                'unique_together': {('empresa', 'codigo_principal')},
            },
        ),
    ]
