# Generated by Django 4.2.27 on 2026-03-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos/", verbose_name="imagen"
            ),
        ),
    ]
