# Generated by Django 4.2.27 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_alter_producto_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="controla_caducidad",
            field=models.BooleanField(
                default=False,
                help_text="Activa control de fecha de caducidad para productos perecibles",
                verbose_name="controla caducidad",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="dias_alerta_caducidad",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Días antes del vencimiento para alertar productos por caducar",
                verbose_name="días alerta caducidad",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="exige_lote",
            field=models.BooleanField(
                default=False,
                help_text="Obliga a registrar número de lote en entradas y salidas de inventario",
                verbose_name="exige lote",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="vida_util_dias",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Vida útil referencial del producto para sugerir fecha de caducidad",
                null=True,
                verbose_name="vida útil en días",
            ),
        ),
    ]
