# Generated by Django 4.2.27 on 2026-03-08 16:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0001_initial"),
        ("ventas", "0001_initial"),
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0003_empresa_onboarding_completado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, verbose_name="número / código"),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nombre descriptivo"
                    ),
                ),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="capacidad (personas)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("LIBRE", "Libre"),
                            ("OCUPADA", "Ocupada"),
                            ("RESERVADA", "Reservada"),
                        ],
                        default="LIBRE",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesas",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "mesa",
                "verbose_name_plural": "mesas",
                "ordering": ["zona", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonas",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "zona",
                "verbose_name_plural": "zonas",
                "ordering": ["orden", "nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pedido",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="número de pedido"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MESA", "Mesa"),
                            ("MOSTRADOR", "Mostrador / Barra"),
                            ("PARA_LLEVAR", "Para llevar"),
                            ("DELIVERY", "Delivery"),
                        ],
                        default="MESA",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_PREPARACION", "En preparación"),
                            ("LISTO", "Listo para entregar"),
                            ("PAGADO", "Pagado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ABIERTO",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "personas",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="número de personas"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="IVA",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="fecha apertura"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha cierre"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha modificación"
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="ventas.caja",
                        verbose_name="caja",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="pedidos.mesa",
                        verbose_name="mesa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_tomados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedido_origen",
                        to="ventas.venta",
                        verbose_name="venta generada",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
                "ordering": ["-fecha_apertura"],
            },
        ),
        migrations.AddField(
            model_name="mesa",
            name="zona",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mesas",
                to="pedidos.zona",
                verbose_name="zona",
            ),
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="precio unitario"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="subtotal"
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="IVA",
                    ),
                ),
                (
                    "notas",
                    models.CharField(
                        blank=True,
                        help_text="Ej: sin cebolla, término medio, etc.",
                        max_length=200,
                        verbose_name="notas / modificaciones",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PREPARACION", "En preparación"),
                            ("LISTO", "Listo"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "fecha_agregado",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="fecha agregado"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="pedidos.pedido",
                        verbose_name="pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_pedido",
                        to="productos.producto",
                        verbose_name="producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="tomado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle de pedido",
                "verbose_name_plural": "detalles de pedido",
                "ordering": ["fecha_agregado"],
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["empresa", "estado"], name="pedidos_ped_empresa_567868_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["mesa", "estado"], name="pedidos_ped_mesa_id_ead212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(fields=["uuid"], name="pedidos_ped_uuid_21c858_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mesa",
            unique_together={("empresa", "numero")},
        ),
    ]
