# Generated by Django 4.2.27 on 2026-03-10 06:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0003_empresa_onboarding_completado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, verbose_name="número")),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("VENTA", "Venta"),
                            ("COMPRA", "Compra"),
                            ("PAGO", "Pago"),
                            ("COBRO", "Cobro"),
                            ("AJUSTE", "Ajuste"),
                            ("APERTURA", "Apertura"),
                            ("CIERRE", "Cierre"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=500, verbose_name="descripción"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Nro. factura, orden, etc.",
                        max_length=200,
                        verbose_name="referencia",
                    ),
                ),
                (
                    "bloqueado",
                    models.BooleanField(
                        default=False,
                        help_text="No permite edición ni reversión",
                        verbose_name="bloqueado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asientos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asientos",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "asiento contable",
                "verbose_name_plural": "asientos contables",
                "ordering": ["-fecha", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="código")),
                ("nombre", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PASIVO", "Pasivo"),
                            ("PATRIMONIO", "Patrimonio"),
                            ("INGRESO", "Ingreso"),
                            ("GASTO", "Gasto"),
                            ("COSTO", "Costo"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[
                            ("DEUDORA", "Deudora (Débito+)"),
                            ("ACREEDORA", "Acreedora (Crédito+)"),
                        ],
                        default="DEUDORA",
                        max_length=15,
                        verbose_name="naturaleza",
                    ),
                ),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(default=1, verbose_name="nivel"),
                ),
                (
                    "es_hoja",
                    models.BooleanField(
                        default=True, verbose_name="es hoja (acepta movimientos)"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_contables",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="contabilidad.cuentacontable",
                        verbose_name="cuenta padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta contable",
                "verbose_name_plural": "cuentas contables",
                "ordering": ["codigo"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="LineaAsiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="descripción"
                    ),
                ),
                (
                    "debe",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="débito",
                    ),
                ),
                (
                    "haber",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="crédito",
                    ),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="contabilidad.asientocontable",
                        verbose_name="asiento",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas",
                        to="contabilidad.cuentacontable",
                        verbose_name="cuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de asiento",
                "verbose_name_plural": "líneas de asiento",
                "ordering": ["id"],
            },
        ),
    ]
