# Generated by Django 4.2.27 on 2026-03-10 06:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facturacion", "0006_add_nota_debito_models"),
        ("empresas", "0003_empresa_onboarding_completado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="número de cotización"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de emisión",
                    ),
                ),
                (
                    "fecha_validez",
                    models.DateField(
                        blank=True, null=True, verbose_name="válida hasta"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "descuento_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="descuento total",
                    ),
                ),
                (
                    "subtotal_iva_0",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal IVA 0%",
                    ),
                ),
                (
                    "subtotal_iva_12",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal IVA 12%",
                    ),
                ),
                (
                    "subtotal_iva_15",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal IVA 15%",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="IVA",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada al cliente"),
                            ("ACEPTADA", "Aceptada"),
                            ("RECHAZADA", "Rechazada"),
                            ("VENCIDA", "Vencida"),
                            ("FACTURADA", "Convertida a factura"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "condiciones",
                    models.TextField(
                        blank=True, verbose_name="condiciones de pago / entrega"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "factura",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizacion_origen",
                        to="facturacion.factura",
                        verbose_name="factura generada",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotización",
                "verbose_name_plural": "cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=300, verbose_name="descripción"),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=25, verbose_name="código"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=12,
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="precio unitario"
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="descuento",
                    ),
                ),
                (
                    "tarifa_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="tarifa IVA %",
                    ),
                ),
                (
                    "precio_total_sin_impuesto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "valor_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="valor IVA",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cotizaciones.cotizacion",
                        verbose_name="cotización",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "ítem de cotización",
                "verbose_name_plural": "ítems de cotización",
                "ordering": ["id"],
            },
        ),
    ]
