# Generated by Django 4.2.27 on 2026-01-30 04:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('es_principal', models.BooleanField(default=False, verbose_name='bodega principal')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad enviada')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='cantidad recibida')),
            ],
            options={
                'verbose_name': 'detalle de transferencia',
                'verbose_name_plural': 'detalles de transferencia',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('SALIDA_VENTA', 'Salida por Venta'), ('AJUSTE_ENTRADA', 'Ajuste Entrada'), ('AJUSTE_SALIDA', 'Ajuste Salida'), ('TRANSFERENCIA_SALIDA', 'Transferencia Salida'), ('TRANSFERENCIA_ENTRADA', 'Transferencia Entrada'), ('DEVOLUCION_ENTRADA', 'Devolución Entrada'), ('DEVOLUCION_SALIDA', 'Devolución Salida')], max_length=30, verbose_name='tipo de movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12, verbose_name='costo unitario')),
                ('venta_id', models.CharField(blank=True, max_length=50, verbose_name='ID venta')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='documento referencia')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha movimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='cantidad')),
                ('costo_promedio', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12, verbose_name='costo promedio')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'stock de producto',
                'verbose_name_plural': 'stock de productos',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transferencia', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='fecha recepción')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='inventarios.bodega', verbose_name='bodega destino')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='inventarios.bodega', verbose_name='bodega origen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'transferencia de inventario',
                'verbose_name_plural': 'transferencias de inventario',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
