# Generated by Django 4.2.27 on 2026-01-30 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciainventario',
            name='usuario_envia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='usuario envía'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='usuario_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='usuario recibe'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventarios.bodega', verbose_name='bodega'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_bodegas', to='productos.producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventarios.bodega', verbose_name='bodega'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventarios.transferenciainventario', verbose_name='transferencia'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddIndex(
            model_name='stockproducto',
            index=models.Index(fields=['producto', 'bodega'], name='inventarios_product_fefef4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockproducto',
            unique_together={('producto', 'bodega')},
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'fecha_movimiento'], name='inventarios_empresa_5b40b1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'bodega'], name='inventarios_product_9ef3de_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['venta_id'], name='inventarios_venta_i_287562_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bodega',
            unique_together={('empresa', 'codigo')},
        ),
    ]
