# Generated by Django 4.2.27 on 2026-08-05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_initial'),
        ('productos', '0006_producto_caducidad_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=80, verbose_name='número de lote')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cantidad disponible')),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12, verbose_name='costo unitario')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], default='DISPONIBLE', max_length=20, verbose_name='estado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_inventario', to='inventarios.bodega', verbose_name='bodega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_inventario', to='empresas.empresa', verbose_name='empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_inventario', to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'lote de inventario',
                'verbose_name_plural': 'lotes de inventario',
                'ordering': ['fecha_caducidad', 'numero_lote'],
                'unique_together': {('empresa', 'producto', 'bodega', 'numero_lote')},
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventarios.loteinventario', verbose_name='lote'),
        ),
        migrations.AddIndex(
            model_name='loteinventario',
            index=models.Index(fields=['empresa', 'producto', 'bodega'], name='inventarios_l_empresa_f14c95_idx'),
        ),
        migrations.AddIndex(
            model_name='loteinventario',
            index=models.Index(fields=['fecha_caducidad', 'estado'], name='inventarios_fech_ca_1f1cbf_idx'),
        ),
    ]
