# Generated by Django 4.2.27 on 2026-09-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0003_loteinventario_and_movimiento_lote"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loteinventario",
            new_name="inventarios_empresa_8f6987_idx",
            old_name="inventarios_l_empresa_f14c95_idx",
        ),
        migrations.RenameIndex(
            model_name="loteinventario",
            new_name="inventarios_fecha_c_813470_idx",
            old_name="inventarios_fech_ca_1f1cbf_idx",
        ),
    ]
