# Generated by Django 4.2.27 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_rename_inventarios_l_empresa_f14c95_idx_inventarios_empresa_8f6987_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='idempotency_key',
            field=models.CharField(
                blank=True,
                help_text='Clave opcional para evitar duplicar reintentos del mismo movimiento.',
                max_length=220,
                null=True,
                verbose_name='clave de idempotencia',
            ),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.UniqueConstraint(
                condition=models.Q(('idempotency_key__isnull', False)),
                fields=('empresa', 'idempotency_key'),
                name='uniq_movimiento_inventario_idempotency',
            ),
        ),
    ]
