# Generated by Django 4.2.27 on 2026-03-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0003_empresa_onboarding_completado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(max_length=20, verbose_name="cédula / pasaporte"),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="apellidos"),
                ),
                ("cargo", models.CharField(max_length=150, verbose_name="cargo")),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="departamento"
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("INDEFINIDO", "Contrato Indefinido"),
                            ("FIJO", "Contrato a Plazo Fijo"),
                            ("OBRA", "Por Obra o Servicio"),
                            ("HONORARIOS", "Honorarios Profesionales"),
                            ("PASANTIA", "Pasantía"),
                        ],
                        default="INDEFINIDO",
                        max_length=20,
                        verbose_name="tipo contrato",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_ingreso", models.DateField(verbose_name="fecha ingreso")),
                (
                    "fecha_salida",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha salida"
                    ),
                ),
                (
                    "sueldo_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="sueldo base"
                    ),
                ),
                (
                    "afiliado_iess",
                    models.BooleanField(default=True, verbose_name="afiliado IESS"),
                ),
                (
                    "numero_iess",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="número afiliación IESS"
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="cuenta bancaria pago"
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="banco"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "empleado",
                "verbose_name_plural": "empleados",
                "ordering": ["apellidos", "nombres"],
                "unique_together": {("empresa", "cedula")},
            },
        ),
        migrations.CreateModel(
            name="RolPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                ("mes", models.PositiveSmallIntegerField(verbose_name="mes")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("APROBADO", "Aprobado"),
                            ("PAGADO", "Pagado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "sueldo_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="sueldo base",
                    ),
                ),
                (
                    "horas_extra_25",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="horas extra 25%",
                    ),
                ),
                (
                    "horas_extra_100",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="horas extra 100%",
                    ),
                ),
                (
                    "comisiones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="comisiones",
                    ),
                ),
                (
                    "bonos",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="bonos"
                    ),
                ),
                (
                    "otros_ingresos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="otros ingresos",
                    ),
                ),
                (
                    "aporte_patronal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="aporte patronal IESS 12.15%",
                    ),
                ),
                (
                    "decimo_tercero",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="décimo tercero",
                    ),
                ),
                (
                    "decimo_cuarto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="décimo cuarto",
                    ),
                ),
                (
                    "fondos_reserva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="fondos de reserva",
                    ),
                ),
                (
                    "vacaciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="vacaciones",
                    ),
                ),
                (
                    "aporte_personal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="aporte personal IESS 9.45%",
                    ),
                ),
                (
                    "impuesto_renta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="impuesto a la renta retenido",
                    ),
                ),
                (
                    "anticipos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="anticipos",
                    ),
                ),
                (
                    "otros_descuentos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="otros descuentos",
                    ),
                ),
                (
                    "total_ingresos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="total ingresos",
                    ),
                ),
                (
                    "total_descuentos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="total descuentos",
                    ),
                ),
                (
                    "liquido_a_pagar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="líquido a pagar",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles_pago",
                        to="nomina.empleado",
                        verbose_name="empleado",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_pago",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "rol de pago",
                "verbose_name_plural": "roles de pago",
                "ordering": ["-anio", "-mes", "empleado__apellidos"],
                "unique_together": {("empresa", "empleado", "anio", "mes")},
            },
        ),
    ]
