# Generated by Django 4.2.27 on 2026-06-23 03:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('empresas', '0007_alter_empresa_password_certificado'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolpago',
            name='aporte_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='aporte patronal IESS'),
        ),
        migrations.AlterField(
            model_name='rolpago',
            name='aporte_personal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='aporte personal IESS'),
        ),
        migrations.CreateModel(
            name='RubroNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, verbose_name='código')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESCUENTO', 'Descuento'), ('PROVISION', 'Provisión')], max_length=15, verbose_name='tipo')),
                ('aplica_iess', models.BooleanField(default=False, verbose_name='aplica IESS')),
                ('aplica_ir', models.BooleanField(default=False, verbose_name='aplica impuesto a la renta')),
                ('es_recurrente', models.BooleanField(default=True, verbose_name='puede ser recurrente')),
                ('automatico', models.BooleanField(default=False, verbose_name='automático del sistema')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveSmallIntegerField(default=100, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros_nomina', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'rubro de nómina',
                'verbose_name_plural': 'rubros de nómina',
                'ordering': ['tipo', 'orden', 'nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PagoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='referencia')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_nomina', to='bancos.cuentabancaria')),
                ('movimiento_bancario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_nomina', to='bancos.movimientobancario')),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_nomina', to='nomina.rolpago')),
            ],
            options={
                'verbose_name': 'pago de rol',
                'verbose_name_plural': 'pagos de roles',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRolPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESCUENTO', 'Descuento'), ('PROVISION', 'Provisión')], max_length=15, verbose_name='tipo')),
                ('codigo', models.CharField(max_length=40, verbose_name='código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor total')),
                ('aplica_iess', models.BooleanField(default=False, verbose_name='aplica IESS')),
                ('aplica_ir', models.BooleanField(default=False, verbose_name='aplica impuesto a la renta')),
                ('automatico', models.BooleanField(default=False, verbose_name='automático')),
                ('orden', models.PositiveSmallIntegerField(default=100, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.rolpago')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_rol', to='nomina.rubronomina')),
            ],
            options={
                'verbose_name': 'detalle de rol',
                'verbose_name_plural': 'detalles de rol',
                'ordering': ['tipo', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoEmpleadoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha fin')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_nomina', to='nomina.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_empleado_nomina', to='empresas.empresa')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_empleado', to='nomina.rubronomina')),
            ],
            options={
                'verbose_name': 'concepto recurrente de empleado',
                'verbose_name_plural': 'conceptos recurrentes de empleados',
                'ordering': ['empleado__apellidos', 'rubro__orden'],
            },
        ),
        migrations.CreateModel(
            name='ParametroNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('sbu', models.DecimalField(decimal_places=2, default=Decimal('460.00'), max_digits=10, verbose_name='salario básico unificado')),
                ('aporte_personal_iess', models.DecimalField(decimal_places=4, default=Decimal('0.0945'), max_digits=6, verbose_name='aporte personal IESS')),
                ('aporte_patronal_iess', models.DecimalField(decimal_places=4, default=Decimal('0.1215'), max_digits=6, verbose_name='aporte patronal IESS')),
                ('decimo_tercero_factor', models.DecimalField(decimal_places=6, default=Decimal('0.083333'), max_digits=8, verbose_name='factor décimo tercero')),
                ('vacaciones_factor', models.DecimalField(decimal_places=6, default=Decimal('0.041667'), max_digits=8, verbose_name='factor vacaciones')),
                ('fondo_reserva_factor', models.DecimalField(decimal_places=6, default=Decimal('0.083333'), max_digits=8, verbose_name='factor fondos de reserva')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_nomina', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'parámetro de nómina',
                'verbose_name_plural': 'parámetros de nómina',
                'ordering': ['-anio'],
                'unique_together': {('empresa', 'anio')},
            },
        ),
    ]
