# Generated by Django 4.2.27 on 2026-06-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_alter_rolpago_aporte_patronal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoempleadonomina',
            name='meses_duracion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='meses de duración'),
        ),
        migrations.AddField(
            model_name='conceptoempleadonomina',
            name='permanente',
            field=models.BooleanField(default=True, verbose_name='recurrencia permanente'),
        ),
    ]
