# Generated by Django 4.2.27 on 2026-04-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0006_notificacion'),
        ('usuarios', '0003_add_password_reset_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('DISCOUNT', 'Descuento'), ('APPROVAL', 'Aprobacion'), ('ALERT', 'Alerta')], max_length=20)),
                ('criterios', models.JSONField(blank=True, default=dict)),
                ('accion', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='empresas.empresa')),
            ],
            options={
                'db_table': 'core_policy_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ORDER_TO_CASH', 'Order to Cash'), ('PROCURE_TO_PAY', 'Procure to Pay')], max_length=30)),
                ('estados', models.JSONField(blank=True, default=list)),
                ('transiciones', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='empresas.empresa')),
            ],
            options={
                'db_table': 'core_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_estado', models.CharField(max_length=50)),
                ('a_estado', models.CharField(max_length=50)),
                ('condicion', models.JSONField(blank=True, default=dict)),
                ('ejecutor_rol', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='core.workflow')),
            ],
            options={
                'db_table': 'core_workflow_transition',
                'unique_together': {('workflow', 'de_estado', 'a_estado')},
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_documento', models.CharField(max_length=80)),
                ('estado_actual', models.CharField(max_length=50)),
                ('iniciado_at', models.DateTimeField(auto_now_add=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_instances', to='empresas.empresa')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_instances_started', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.workflow')),
            ],
            options={
                'db_table': 'core_process_instance',
                'ordering': ['-iniciado_at'],
            },
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_estado', models.CharField(max_length=50)),
                ('a_estado', models.CharField(max_length=50)),
                ('razon', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='core.processinstance')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_changes_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_state_change',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(max_length=40)),
                ('documento_id', models.CharField(max_length=40)),
                ('aprobador_requerido_rol', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=12)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('razon', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('aprobador_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tickets', to='empresas.empresa')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_approval_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=60)),
                ('modulo', models.CharField(max_length=40)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['empresa', 'created_at'], name='idx_audit_emp_date'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario', 'created_at'], name='idx_audit_usr_date'),
        ),
        migrations.AddIndex(
            model_name='approvalticket',
            index=models.Index(fields=['empresa', 'estado'], name='idx_approval_emp_est'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['empresa', 'estado_actual'], name='idx_proc_emp_estado'),
        ),
        migrations.AddIndex(
            model_name='policyrule',
            index=models.Index(fields=['empresa', 'tipo', 'activa'], name='idx_policy_emp_tipo'),
        ),
    ]
