# Generated by Django 4.2.27 on 2026-01-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'Identificación del Exterior')], default='05', max_length=2, verbose_name='tipo de identificación')),
                ('identificacion', models.CharField(max_length=20, verbose_name='identificación')),
                ('razon_social', models.CharField(max_length=300, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, verbose_name='nombre comercial')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('celular', models.CharField(blank=True, max_length=15, verbose_name='celular')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['empresa', 'activo'], name='clientes_cl_empresa_8e803f_idx'), models.Index(fields=['identificacion'], name='clientes_cl_identif_add71b_idx')],
                'unique_together': {('empresa', 'identificacion')},
            },
        ),
    ]
