# Generated by Django 4.2.27 on 2026-06-12 01:10

import apps.firmas.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0006_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFirmaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('PERSONA_NATURAL', 'Persona Natural'), ('REPRESENTANTE_LEGAL', 'Representante Legal'), ('MIEMBRO_EMPRESA', 'Miembro de Empresa')], max_length=30, verbose_name='tipo de solicitud')),
                ('first_name', models.CharField(max_length=120, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=120, verbose_name='apellidos')),
                ('identification', models.CharField(max_length=20, verbose_name='cédula')),
                ('fingerprint_code', models.CharField(max_length=30, verbose_name='código dactilar')),
                ('ruc', models.CharField(blank=True, max_length=20, verbose_name='RUC')),
                ('business_name', models.CharField(blank=True, max_length=180, verbose_name='razón social')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono/celular')),
                ('province', models.CharField(max_length=80, verbose_name='provincia')),
                ('city', models.CharField(max_length=80, verbose_name='ciudad')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('validity', models.CharField(choices=[('15_DIAS', '15 días'), ('1_MES', '1 mes'), ('1_ANIO', '1 año'), ('2_ANIOS', '2 años'), ('3_ANIOS', '3 años'), ('4_ANIOS', '4 años'), ('5_ANIOS', '5 años')], max_length=20, verbose_name='vigencia solicitada')),
                ('container_type', models.CharField(blank=True, choices=[('ARCHIVO', 'Archivo'), ('NUBE', 'Nube'), ('TOKEN', 'Token')], max_length=20, verbose_name='tipo de contenedor')),
                ('wants_erp', models.BooleanField(default=False, verbose_name='también desea ERP')),
                ('interested_plan', models.CharField(choices=[('BASICO', 'Básico'), ('PROFESIONAL', 'Profesional'), ('EMPRESARIAL', 'Empresarial'), ('SOLO_FIRMA', 'Solo firma')], max_length=20, verbose_name='plan de interés')),
                ('status', models.CharField(choices=[('NUEVA', 'Nueva'), ('CONTACTADO', 'Contactado'), ('DOCUMENTOS_PENDIENTES', 'Documentos pendientes'), ('EN_REVISION', 'En revisión'), ('ENVIADA_PROVEEDOR', 'Enviada a proveedor'), ('EMITIDA', 'Emitida'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='NUEVA', max_length=30, verbose_name='estado')),
                ('source', models.CharField(choices=[('LANDING', 'Landing'), ('WHATSAPP', 'WhatsApp'), ('REFERIDO_CONTADOR', 'Referido contador'), ('CLIENTE_ERP', 'Cliente ERP'), ('REDES_SOCIALES', 'Redes sociales'), ('MANUAL_ADMINISTRATIVO', 'Manual administrativo')], default='MANUAL_ADMINISTRATIVO', max_length=30, verbose_name='origen')),
                ('provider', models.CharField(blank=True, choices=[('UANATACA', 'Uanataca'), ('NEXUS', 'Nexus'), ('OTRO', 'Otro')], max_length=20, verbose_name='proveedor')),
                ('internal_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='costo interno')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='precio de venta')),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='margen')),
                ('internal_notes', models.TextField(blank=True, verbose_name='observaciones internas')),
                ('provider_request_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='id solicitud proveedor')),
                ('emitted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de emisión')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='motivo de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_firma', to='empresas.empresa', verbose_name='empresa')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_firma', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'solicitud de firma electrónica',
                'verbose_name_plural': 'solicitudes de firma electrónica',
                'db_table': 'electronic_signature_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoSolicitudFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=30, verbose_name='estado anterior')),
                ('new_status', models.CharField(max_length=30, verbose_name='nuevo estado')),
                ('comment', models.TextField(blank=True, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de cambio')),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_firma', to=settings.AUTH_USER_MODEL, verbose_name='usuario que cambió')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='firmas.solicitudfirmaelectronica', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'historial de estado de firma',
                'verbose_name_plural': 'historial de estados de firma',
                'db_table': 'electronic_signature_request_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSolicitudFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CEDULA_ANVERSO', 'Anverso de cédula'), ('CEDULA_REVERSO', 'Reverso de cédula'), ('SELFIE_CEDULA', 'Selfie con cédula'), ('RUC_PDF', 'RUC PDF'), ('NOMBRAMIENTO_REPRESENTANTE', 'Nombramiento representante legal'), ('CARTA_AUTORIZACION', 'Carta de autorización'), ('CEDULA_REPRESENTANTE', 'Cédula representante legal'), ('VIDEO_AUTORIZACION', 'Video de autorización')], max_length=40, verbose_name='tipo de documento')),
                ('file', models.FileField(upload_to=apps.firmas.models.firma_document_upload_to, verbose_name='archivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='nombre de archivo')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='tipo MIME')),
                ('status', models.CharField(choices=[('CARGADO', 'Cargado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='CARGADO', max_length=20, verbose_name='estado')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='firmas.solicitudfirmaelectronica', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'documento de solicitud de firma',
                'verbose_name_plural': 'documentos de solicitud de firma',
                'db_table': 'electronic_signature_request_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudfirmaelectronica',
            index=models.Index(fields=['company', 'status'], name='electronic__company_0b78c0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudfirmaelectronica',
            index=models.Index(fields=['request_type', 'status'], name='electronic__request_20106b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudfirmaelectronica',
            index=models.Index(fields=['created_at'], name='electronic__created_d97126_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudfirmaelectronica',
            index=models.Index(fields=['source'], name='electronic__source_01008b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosolicitudfirma',
            index=models.Index(fields=['request', 'document_type'], name='electronic__request_b0fd48_idx'),
        ),
    ]
