# Generated by Django 4.2.27 on 2026-06-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDemoERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180, verbose_name='negocio')),
                ('contact_name', models.CharField(max_length=160, verbose_name='contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono/celular')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='ciudad')),
                ('business_type', models.CharField(blank=True, max_length=120, verbose_name='tipo de negocio')),
                ('interested_plan', models.CharField(choices=[('BASICO', 'Básico'), ('PROFESIONAL', 'Profesional'), ('EMPRESARIAL', 'Empresarial'), ('NO_SEGURO', 'No estoy seguro')], default='NO_SEGURO', max_length=20, verbose_name='plan de interés')),
                ('needs_signature', models.BooleanField(default=False, verbose_name='necesita firma electrónica')),
                ('already_has_signature', models.BooleanField(default=False, verbose_name='ya tiene firma electrónica')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('source', models.CharField(choices=[('LANDING', 'Landing'), ('PRECIOS', 'Planes y precios'), ('WHATSAPP', 'WhatsApp'), ('REFERIDO', 'Referido'), ('OTRO', 'Otro')], default='LANDING', max_length=20, verbose_name='origen')),
                ('status', models.CharField(choices=[('NUEVA', 'Nueva'), ('CONTACTADO', 'Contactado'), ('DEMO_AGENDADA', 'Demo agendada'), ('CONVERTIDA', 'Convertida'), ('DESCARTADA', 'Descartada')], default='NUEVA', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'solicitud de demo ERP',
                'verbose_name_plural': 'solicitudes de demo ERP',
                'db_table': 'erp_demo_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='erp_demo_re_status_cf9777_idx'), models.Index(fields=['source'], name='erp_demo_re_source_ecc19c_idx'), models.Index(fields=['interested_plan'], name='erp_demo_re_interes_6825c1_idx')],
            },
        ),
    ]
