# Generated by Django 4.2.27 on 2026-06-15 22:38

import apps.firmas.models
import apps.firmas.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0003_solicitud_firma_wizard_publico'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitudfirmaelectronica',
            new_name='electronic__request_86f6ce_idx',
            old_name='electronic__request_d29721_idx',
        ),
        migrations.AlterField(
            model_name='documentosolicitudfirma',
            name='file',
            field=models.FileField(storage=apps.firmas.storage.SignatureDocumentStorage(), upload_to=apps.firmas.models.firma_document_upload_to, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='solicitudfirmaelectronica',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico secundario'),
        ),
    ]
