# Generated by Django 4.2.27 on 2026-06-19 17:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_promotional_values(apps, schema_editor):
    Promotion = apps.get_model('firmas', 'FirmaPromocionElectronica')
    for promotion in Promotion.objects.all().iterator():
        promotion.discount_type = 'FINAL_PRICE'
        promotion.discount_value = promotion.promotional_price
        promotion.save(update_fields=['discount_type', 'discount_value'])


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0005_precios_promociones_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaprecioelectronica',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='firmapromocionelectronica',
            name='discount_type',
            field=models.CharField(choices=[('FINAL_PRICE', 'Precio final con IVA'), ('PERCENTAGE', 'Porcentaje sobre precio sin IVA')], default='FINAL_PRICE', max_length=20),
        ),
        migrations.AddField(
            model_name='firmapromocionelectronica',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='firmapromocionelectronica',
            name='group_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.RunPython(backfill_promotional_values, migrations.RunPython.noop),
        migrations.AddField(
            model_name='solicitudfirmaelectronica',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='solicitudfirmaelectronica',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudfirmaelectronica',
            name='subtotal_without_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudfirmaelectronica',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudfirmaelectronica',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='FirmaCuponElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED_AMOUNT', 'Monto fijo')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_total_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prices', models.ManyToManyField(blank=True, related_name='coupons', to='firmas.firmaprecioelectronica')),
            ],
            options={
                'db_table': 'electronic_signature_coupons',
                'ordering': ['-active', '-start_date', 'code'],
            },
        ),
        migrations.AddField(
            model_name='solicitudfirmaelectronica',
            name='coupon_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='firmas.firmacuponelectronico'),
        ),
        migrations.CreateModel(
            name='FirmaCuponUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(db_index=True, max_length=160)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='firmas.firmacuponelectronico')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_use', to='firmas.solicitudfirmaelectronica')),
            ],
            options={
                'db_table': 'electronic_signature_coupon_uses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coupon', 'customer_key'], name='electronic__coupon__b0943b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='firmacuponelectronico',
            index=models.Index(fields=['code', 'active', 'start_date', 'end_date'], name='electronic__code_e37ff6_idx'),
        ),
    ]
