# Generated by Django 4.2.27 on 2026-06-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0008_consentimiento_firma_electronica'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaPagoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('PAYPHONE', 'PayPhone')], default='PAYPHONE', max_length=30, verbose_name='proveedor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REDIRECTED', 'Redirigido'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='moneda')),
                ('client_transaction_id', models.CharField(max_length=80, unique=True, verbose_name='transacción cliente')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=120, verbose_name='transacción proveedor')),
                ('payment_url', models.URLField(blank=True, max_length=1000, verbose_name='url de pago')),
                ('raw_request', models.JSONField(blank=True, default=dict, verbose_name='request proveedor')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='response proveedor')),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualización')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='firmas.solicitudfirmaelectronica', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'pago de firma electrónica',
                'verbose_name_plural': 'pagos de firma electrónica',
                'db_table': 'electronic_signature_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'provider', 'status'], name='electronic__request_772806_idx'), models.Index(fields=['client_transaction_id'], name='electronic__client__bbc16a_idx')],
            },
        ),
    ]
