# Generated by Django 4.2.27 on 2026-06-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0009_firmapagoelectronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmapagoelectronico',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='código autorización'),
        ),
        migrations.AddField(
            model_name='firmapagoelectronico',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto firma'),
        ),
        migrations.AddField(
            model_name='firmapagoelectronico',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='recargo transacción'),
        ),
        migrations.AddField(
            model_name='firmapagoelectronico',
            name='processing_fee_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA recargo transacción'),
        ),
        migrations.AlterField(
            model_name='firmapagoelectronico',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto total'),
        ),
    ]
