# Generated by Django 4.2.27 on 2026-06-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_precio'),
        ('firmas', '0010_firmapagoelectronico_authorization_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaprecioelectronica',
            name='producto_erp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_catalogo_firma_electronica', to='productos.producto', verbose_name='producto ERP'),
        ),
    ]
