# Generated by Django 4.2.27 on 2026-01-30 04:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=300, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, verbose_name='nombre comercial')),
                ('tipo_contribuyente', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('SOCIEDAD', 'Sociedad'), ('PUBLICA', 'Institución Pública')], default='NATURAL', max_length=20, verbose_name='tipo de contribuyente')),
                ('contribuyente_especial', models.CharField(blank=True, help_text='Si es contribuyente especial', max_length=10, verbose_name='número contribuyente especial')),
                ('obligado_contabilidad', models.BooleanField(default=False, verbose_name='obligado a llevar contabilidad')),
                ('direccion_matriz', models.TextField(verbose_name='dirección matriz')),
                ('telefono', models.CharField(max_length=15, verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', help_text='1=Pruebas, 2=Producción', max_length=1, verbose_name='ambiente')),
                ('certificado_digital', models.FileField(blank=True, help_text='Archivo .p12 o .pfx del certificado de firma electrónica', null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['p12', 'pfx'])], verbose_name='certificado digital')),
                ('password_certificado', models.CharField(blank=True, help_text='Contraseña del certificado digital (se guarda encriptada)', max_length=255, verbose_name='contraseña del certificado')),
                ('fecha_vencimiento_certificado', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento del certificado')),
                ('establecimiento_codigo', models.CharField(default='001', help_text='Código de 3 dígitos', max_length=3, verbose_name='código de establecimiento')),
                ('punto_emision_codigo', models.CharField(default='001', help_text='Código de 3 dígitos', max_length=3, verbose_name='código punto de emisión')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='logo')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('verificada', models.BooleanField(default=False, help_text='Verificada por el SRI', verbose_name='verificada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 3 dígitos', max_length=3, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('direccion', models.TextField(verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'establecimiento',
                'verbose_name_plural': 'establecimientos',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PuntoEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 3 dígitos', max_length=3, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_emision', to='empresas.establecimiento', verbose_name='establecimiento')),
            ],
            options={
                'verbose_name': 'punto de emisión',
                'verbose_name_plural': 'puntos de emisión',
                'ordering': ['codigo'],
                'unique_together': {('establecimiento', 'codigo')},
            },
        ),
    ]
