# Generated by Django 4.2.27 on 2026-03-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="agente_retencion",
            field=models.BooleanField(
                default=False, verbose_name="agente de retención"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, verbose_name="ciudad"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="exportador",
            field=models.BooleanField(default=False, verbose_name="exportador"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="firmado_automatico",
            field=models.BooleanField(default=True, verbose_name="firmado automático"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="gran_contribuyente",
            field=models.BooleanField(default=False, verbose_name="gran contribuyente"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="mensaje_personalizado",
            field=models.TextField(blank=True, verbose_name="mensaje personalizado"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="regimen_rimpe",
            field=models.BooleanField(
                default=False, verbose_name="contribuyente régimen RIMPE"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tipo_exportador",
            field=models.CharField(
                blank=True,
                choices=[("HABITUAL", "Habitual"), ("NO_HABITUAL", "No habitual")],
                max_length=20,
                verbose_name="tipo exportador",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tipo_rimpe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RIMPE_EMPRENDEDOR", "Contribuyente Régimen RIMPE"),
                    ("RIMPE_POPULAR", "Negocio Popular Régimen RIMPE"),
                ],
                max_length=30,
                verbose_name="tipo RIMPE",
            ),
        ),
    ]
