# Generated by Django 4.2.27 on 2026-03-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_add_configuracion_sri_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="onboarding_completado",
            field=models.BooleanField(
                default=False, verbose_name="onboarding completado"
            ),
        ),
    ]
