# Generated by Django 4.2.27 on 2026-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_empresa_onboarding_completado"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="certificado_data",
            field=models.BinaryField(
                blank=True,
                help_text="Bytes del certificado, persistidos en BD para ambientes con filesystem efímero",
                null=True,
            ),
        ),
    ]
