# Generated by Django 4.2.27 on 2026-03-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_add_certificado_data_binary_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="logo_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
