# Generated by Django 4.2.27 on 2026-03-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_add_logo_data_binary_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ERROR", "Error"),
                            ("ADVERTENCIA", "Advertencia"),
                            ("EXITO", "Éxito"),
                            ("INFO", "Información"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("mensaje", models.TextField(verbose_name="mensaje")),
                (
                    "url",
                    models.CharField(blank=True, max_length=300, verbose_name="url"),
                ),
                ("leida", models.BooleanField(default=False, verbose_name="leída")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
