# Generated by Django 4.2.27 on 2026-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_notificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="password_certificado",
            field=models.CharField(
                blank=True,
                help_text="Contraseña del certificado digital (se guarda encriptada con Fernet)",
                max_length=500,
                verbose_name="contraseña del certificado",
            ),
        ),
    ]
