# Generated by Codex on 2026-07-29

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_alter_empresa_password_certificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="ruc_proveedor_facturacion_electronica",
            field=models.CharField(
                blank=True,
                help_text="RUC del proveedor externo de sistemas o servicios de facturación electrónica.",
                max_length=13,
                validators=[
                    RegexValidator(
                        regex="^\\d{13}$",
                        message="El RUC del proveedor debe tener exactamente 13 dígitos.",
                    )
                ],
                verbose_name="RUC proveedor de facturación electrónica",
            ),
        ),
    ]
