# Generated by Django 4.2.27 on 2026-03-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facturacion", "0006_add_nota_debito_models"),
        ("clientes", "0001_initial"),
        ("empresas", "0003_empresa_onboarding_completado"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaPorCobrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="número de cuenta"
                    ),
                ),
                ("fecha_emision", models.DateField(verbose_name="fecha de emisión")),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="fecha de vencimiento"),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto total"
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="saldo pendiente"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcial"),
                            ("PAGADO", "Pagado"),
                            ("VENCIDA", "Vencida"),
                            ("INCOBRABLE", "Incobrable"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas_por_cobrar",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_por_cobrar",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "factura",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuenta_por_cobrar",
                        to="facturacion.factura",
                        verbose_name="factura origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta por cobrar",
                "verbose_name_plural": "cuentas por cobrar",
                "ordering": ["fecha_vencimiento", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PagoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField(verbose_name="fecha de pago")),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto"
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia bancaria"),
                            ("TARJETA_DEBITO", "Tarjeta débito"),
                            ("TARJETA_CREDITO", "Tarjeta crédito"),
                            ("CHEQUE", "Cheque"),
                            ("OTRO", "Otro"),
                        ],
                        default="EFECTIVO",
                        max_length=20,
                        verbose_name="forma de pago",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="referencia"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="cartera.cuentaporcobrar",
                        verbose_name="cuenta por cobrar",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago de cliente",
                "verbose_name_plural": "pagos de clientes",
                "ordering": ["-fecha_pago"],
            },
        ),
    ]
