# Generated by Django 4.2.27 on 2026-06-24 18:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0005_pagoventa_estado_pago'),
        ('productos', '0005_alter_producto_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bancos', '0001_initial'),
        ('suscripciones', '0009_firmas_superadmin_only'),
        ('empresas', '0007_alter_empresa_password_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='porcentaje recargo tarjeta')),
                ('fee_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='IVA recargo tarjeta')),
                ('auto_generar_venta_firmas', models.BooleanField(default=True, verbose_name='generar venta por firmas pagadas')),
                ('auto_generar_venta_suscripciones', models.BooleanField(default=True, verbose_name='generar venta por suscripciones pagadas')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('caja_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_pagos', to='ventas.caja', verbose_name='caja para ventas online')),
                ('cuenta_payphone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_payphone', to='bancos.cuentabancaria', verbose_name='cuenta PayPhone')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_pagos', to='empresas.empresa', verbose_name='empresa')),
                ('producto_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_pago_firma', to='productos.producto', verbose_name='producto firma electrónica')),
                ('producto_recargo_payphone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_recargo_payphone', to='productos.producto', verbose_name='producto recargo PayPhone')),
                ('producto_suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_pago_suscripcion', to='productos.producto', verbose_name='producto suscripción ERP')),
                ('usuario_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_pagos_online', to=settings.AUTH_USER_MODEL, verbose_name='usuario para ventas online')),
            ],
            options={
                'verbose_name': 'configuración de pagos online',
                'verbose_name_plural': 'configuraciones de pagos online',
                'db_table': 'online_payment_configurations',
            },
        ),
        migrations.CreateModel(
            name='PagoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('FIRMA', 'Firma electrónica'), ('SUSCRIPCION', 'Suscripción ERP'), ('VENTA', 'Venta'), ('CARTERA', 'Cartera'), ('OTRO', 'Otro')], max_length=20, verbose_name='origen')),
                ('origen_id', models.CharField(blank=True, max_length=80, verbose_name='id origen')),
                ('provider', models.CharField(choices=[('PAYPHONE', 'PayPhone')], default='PAYPHONE', max_length=30, verbose_name='proveedor')),
                ('metodo', models.CharField(choices=[('PAYPHONE', 'PayPhone'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('TRANSFERENCIA', 'Transferencia'), ('MANUAL', 'Manual')], default='PAYPHONE', max_length=30, verbose_name='método')),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='estado')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='moneda')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monto base')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='recargo transacción')),
                ('processing_fee_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA recargo')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monto total')),
                ('client_transaction_id', models.CharField(max_length=100, unique=True, verbose_name='transacción cliente')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=120, verbose_name='transacción proveedor')),
                ('authorization_code', models.CharField(blank=True, max_length=120, verbose_name='código autorización')),
                ('raw_request', models.JSONField(blank=True, default=dict, verbose_name='request proveedor')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='response proveedor')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('error_message', models.TextField(blank=True, verbose_name='error proveedor')),
                ('application_error', models.TextField(blank=True, verbose_name='error aplicación interna')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha confirmación')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha aplicación interna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_online', to='empresas.empresa', verbose_name='empresa')),
                ('movimiento_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_online', to='bancos.movimientobancario')),
                ('pago_suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_online', to='suscripciones.pago')),
                ('pago_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_online', to='ventas.pagoventa')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_online', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'pago online',
                'verbose_name_plural': 'pagos online',
                'db_table': 'online_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='online_paym_empresa_b58eac_idx'), models.Index(fields=['origen', 'origen_id'], name='online_paym_origen_be797b_idx'), models.Index(fields=['provider', 'client_transaction_id'], name='online_paym_provide_a488d2_idx'), models.Index(fields=['created_at'], name='online_paym_created_e55f21_idx')],
            },
        ),
    ]
