# Generated by Django 4.2.27 on 2026-06-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoconfiguracion',
            name='fee_percent',
        ),
        migrations.RemoveField(
            model_name='pagoconfiguracion',
            name='fee_tax_rate',
        ),
        migrations.RemoveField(
            model_name='pagoconfiguracion',
            name='producto_firma',
        ),
        migrations.RemoveField(
            model_name='pagoconfiguracion',
            name='producto_recargo_payphone',
        ),
        migrations.RemoveField(
            model_name='pagoconfiguracion',
            name='producto_suscripcion',
        ),
    ]
