# Generated by Django 4.2.27 on 2026-06-17 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firmas', '0005_precios_promociones_firma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='teléfono')),
                ('normalized_phone', models.CharField(max_length=32, verbose_name='teléfono normalizado')),
                ('source_channel', models.CharField(default='whatsapp', max_length=30, verbose_name='canal')),
                ('name', models.CharField(blank=True, max_length=160, verbose_name='nombre')),
                ('company', models.CharField(blank=True, max_length=180, verbose_name='empresa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('interest_type', models.CharField(choices=[('signature', 'Firma electrónica'), ('erp', 'ERP FacturaOF1'), ('invoicing', 'Facturación electrónica'), ('custom_software', 'Desarrollo a medida'), ('automation_ai', 'Automatización e IA'), ('chatbot', 'Chatbots'), ('integration', 'Integraciones'), ('support', 'Soporte'), ('unknown', 'No definido')], default='unknown', max_length=40, verbose_name='tipo de interés')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('requires_human', 'Requiere humano'), ('converted', 'Convertido'), ('closed', 'Cerrado')], default='new', max_length=30, verbose_name='estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='prioridad')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
                ('last_category', models.CharField(blank=True, max_length=40, verbose_name='última categoría')),
                ('last_intent', models.CharField(blank=True, max_length=40, verbose_name='última intención')),
                ('last_ai_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='última confianza IA')),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True, verbose_name='última interacción')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_leads', to=settings.AUTH_USER_MODEL, verbose_name='asesor asignado')),
            ],
            options={
                'verbose_name': 'lead comercial',
                'verbose_name_plural': 'leads comerciales',
                'db_table': 'automation_commercial_leads',
                'ordering': ['-last_interaction_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True, verbose_name='id evento')),
                ('event_type', models.CharField(max_length=80, verbose_name='tipo de evento')),
                ('entity_type', models.CharField(blank=True, max_length=80, verbose_name='tipo de entidad')),
                ('entity_id', models.CharField(blank=True, max_length=80, verbose_name='id entidad')),
                ('idempotency_key', models.CharField(max_length=220, unique=True, verbose_name='clave de idempotencia')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('target_url', models.URLField(blank=True, verbose_name='url destino')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('SKIPPED', 'Omitido')], default='PENDING', max_length=20, verbose_name='estado')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('last_error', models.TextField(blank=True, verbose_name='último error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'evento webhook automation',
                'verbose_name_plural': 'eventos webhook automation',
                'db_table': 'automation_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='automation__event_t_ac47c6_idx'), models.Index(fields=['entity_type', 'entity_id'], name='automation__entity__da2248_idx'), models.Index(fields=['created_at'], name='automation__created_79978d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'Sistema'), ('N8N', 'n8n'), ('USER', 'Usuario'), ('GATEWAY', 'Gateway')], default='N8N', max_length=20, verbose_name='tipo actor')),
                ('actor_id', models.CharField(blank=True, max_length=120, verbose_name='id actor')),
                ('action', models.CharField(max_length=120, verbose_name='acción')),
                ('entity_type', models.CharField(blank=True, max_length=80, verbose_name='tipo entidad')),
                ('entity_id', models.CharField(blank=True, max_length=80, verbose_name='id entidad')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'auditoría automation',
                'verbose_name_plural': 'auditoría automation',
                'db_table': 'automation_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='automation__action_2998c8_idx'), models.Index(fields=['entity_type', 'entity_id'], name='automation__entity__8e1395_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Entrante'), ('OUTBOUND', 'Saliente')], max_length=10, verbose_name='dirección')),
                ('phone', models.CharField(max_length=32, verbose_name='teléfono')),
                ('normalized_phone', models.CharField(max_length=32, verbose_name='teléfono normalizado')),
                ('channel', models.CharField(default='whatsapp', max_length=30, verbose_name='canal')),
                ('message_body', models.TextField(blank=True, verbose_name='mensaje')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('unknown', 'Desconocido')], default='text', max_length=20, verbose_name='tipo de mensaje')),
                ('message_id', models.CharField(blank=True, max_length=160, verbose_name='id mensaje')),
                ('idempotency_key', models.CharField(max_length=220, unique=True, verbose_name='clave de idempotencia')),
                ('category', models.CharField(blank=True, max_length=40, verbose_name='categoría')),
                ('intent', models.CharField(blank=True, max_length=40, verbose_name='intención')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='confianza IA')),
                ('ai_summary', models.TextField(blank=True, verbose_name='resumen IA')),
                ('requires_human', models.BooleanField(default=False, verbose_name='requiere humano')),
                ('template_key', models.CharField(blank=True, max_length=80, verbose_name='plantilla')),
                ('gateway_status', models.CharField(blank=True, max_length=40, verbose_name='estado gateway')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='automation.commerciallead', verbose_name='lead')),
                ('signature_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_interactions', to='firmas.solicitudfirmaelectronica', verbose_name='pedido de firma')),
            ],
            options={
                'verbose_name': 'interacción WhatsApp',
                'verbose_name_plural': 'interacciones WhatsApp',
                'db_table': 'automation_whatsapp_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['normalized_phone', 'channel', 'created_at'], name='automation__normali_5069dc_idx'), models.Index(fields=['direction', 'created_at'], name='automation__directi_9a1cc6_idx'), models.Index(fields=['category', 'intent'], name='automation__categor_d08314_idx'), models.Index(fields=['requires_human'], name='automation__require_92b565_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='commerciallead',
            index=models.Index(fields=['interest_type', 'status'], name='automation__interes_eb25d3_idx'),
        ),
        migrations.AddIndex(
            model_name='commerciallead',
            index=models.Index(fields=['priority', 'status'], name='automation__priorit_0a7ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='commerciallead',
            index=models.Index(fields=['last_interaction_at'], name='automation__last_in_50cfc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='commerciallead',
            constraint=models.UniqueConstraint(fields=('normalized_phone', 'source_channel'), name='uniq_automation_lead_phone_channel'),
        ),
    ]
