# Generated by Django 4.2.27 on 2026-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commerciallead',
            name='uniq_automation_lead_phone_channel',
        ),
        migrations.AddField(
            model_name='commerciallead',
            name='contact_key',
            field=models.CharField(blank=True, max_length=160, verbose_name='clave de contacto'),
        ),
        migrations.AddField(
            model_name='commerciallead',
            name='from_jid',
            field=models.CharField(blank=True, max_length=160, verbose_name='JID remitente'),
        ),
        migrations.AddField(
            model_name='commerciallead',
            name='is_lid',
            field=models.BooleanField(default=False, verbose_name='es LID'),
        ),
        migrations.AddField(
            model_name='commerciallead',
            name='push_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='nombre WhatsApp'),
        ),
        migrations.AddField(
            model_name='commerciallead',
            name='remote_jid',
            field=models.CharField(blank=True, max_length=160, verbose_name='JID chat'),
        ),
        migrations.AddField(
            model_name='commerciallead',
            name='reply_to_jid',
            field=models.CharField(blank=True, max_length=160, verbose_name='JID de respuesta'),
        ),
        migrations.AddField(
            model_name='whatsappinteraction',
            name='contact_key',
            field=models.CharField(blank=True, max_length=160, verbose_name='clave de contacto'),
        ),
        migrations.AddField(
            model_name='whatsappinteraction',
            name='from_jid',
            field=models.CharField(blank=True, max_length=160, verbose_name='JID remitente'),
        ),
        migrations.AddField(
            model_name='whatsappinteraction',
            name='is_lid',
            field=models.BooleanField(default=False, verbose_name='es LID'),
        ),
        migrations.AddField(
            model_name='whatsappinteraction',
            name='push_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='nombre WhatsApp'),
        ),
        migrations.AddField(
            model_name='whatsappinteraction',
            name='remote_jid',
            field=models.CharField(blank=True, max_length=160, verbose_name='JID chat'),
        ),
        migrations.AddField(
            model_name='whatsappinteraction',
            name='reply_to_jid',
            field=models.CharField(blank=True, max_length=160, verbose_name='JID de respuesta'),
        ),
        migrations.AlterField(
            model_name='commerciallead',
            name='normalized_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='teléfono normalizado'),
        ),
        migrations.AlterField(
            model_name='commerciallead',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='whatsappinteraction',
            name='normalized_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='teléfono normalizado'),
        ),
        migrations.AlterField(
            model_name='whatsappinteraction',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='teléfono'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteraction',
            index=models.Index(fields=['contact_key', 'channel', 'created_at'], name='automation__contact_4c13c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='commerciallead',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_phone', ''), _negated=True), fields=('normalized_phone', 'source_channel'), name='uniq_automation_lead_phone_channel'),
        ),
        migrations.AddConstraint(
            model_name='commerciallead',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_key', ''), _negated=True), fields=('contact_key', 'source_channel'), name='uniq_automation_lead_contact_key_channel'),
        ),
    ]
