# Generated by Django 4.2.27 on 2026-06-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_lead_admin_statuses_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_key', models.CharField(db_index=True, max_length=160, verbose_name='clave de contacto')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('privacy_notice_sent_at', models.DateTimeField(verbose_name='aviso de privacidad enviado')),
                ('privacy_notice_version', models.CharField(max_length=60, verbose_name='versión de aviso')),
                ('consent_source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('form', 'Formulario'), ('n8n', 'n8n'), ('other', 'Otro')], default='whatsapp', max_length=30, verbose_name='fuente')),
                ('consent_status', models.CharField(choices=[('informed', 'Informado')], default='informed', max_length=30, verbose_name='estado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_consents', to='automation.commerciallead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'consentimiento/aviso de privacidad automation',
                'verbose_name_plural': 'consentimientos/avisos de privacidad automation',
                'db_table': 'automation_privacy_consents',
                'ordering': ['-privacy_notice_sent_at'],
                'indexes': [models.Index(fields=['lead', 'privacy_notice_sent_at'], name='automation__lead_id_4ff9cb_idx'), models.Index(fields=['consent_source', 'consent_status'], name='automation__consent_a46eb0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='automationprivacyconsent',
            constraint=models.UniqueConstraint(fields=('contact_key', 'privacy_notice_version', 'consent_source'), name='uniq_automation_privacy_contact_version_source'),
        ),
    ]
