# Generated by Django 4.2.27 on 2026-10-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_conversation_handoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerciallead',
            name='bot_resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commerciallead',
            name='human_last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
