# Generated by Django 4.2.27 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_automationwebhookevent_retry_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationwebhookevent',
            name='dispatch_en_curso',
            field=models.BooleanField(db_index=True, default=False, help_text='Claim atómico para evitar despachos concurrentes; no es un estado funcional.', verbose_name='despacho en curso'),
        ),
    ]
