# Generated by Django 4.2.27 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_automationwebhookevent_dispatch_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationwebhookevent',
            name='dispatch_iniciado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
