# Generated by Django 4.2.27 on 2026-09-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_automationwebhookevent_dispatch_timestamp'),
        ('empresas', '0010_alter_empresa_inventario_permite_stock_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationwebhookevent',
            name='empresa',
            field=models.ForeignKey(
                blank=True,
                help_text='Empresa operativa asociada; nulo para eventos globales de plataforma.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='automation_webhook_events',
                to='empresas.empresa',
                verbose_name='empresa contexto',
            ),
        ),
        migrations.AddIndex(
            model_name='automationwebhookevent',
            index=models.Index(fields=['empresa', 'status'], name='automation__empresa_e6502a_idx'),
        ),
    ]
