# Generated by Django 4.2.27 on 2026-01-30 04:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero_cuenta', models.CharField(db_index=True, max_length=50, verbose_name='número de cuenta')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monto pagado')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='saldo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pagada Parcialmente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'cuenta por pagar',
                'verbose_name_plural': 'cuentas por pagar',
                'db_table': 'cuentas_por_pagar',
                'ordering': ['fecha_vencimiento', '-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cantidad')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cantidad recibida')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='descuento')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='aplica IVA')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='porcentaje IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'detalle de orden de compra',
                'verbose_name_plural': 'detalles de orden de compra',
                'db_table': 'detalles_orden_compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cantidad recibida')),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo unitario')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el producto recibido', verbose_name='notas')),
            ],
            options={
                'verbose_name': 'detalle de recepción',
                'verbose_name_plural': 'detalles de recepción',
                'db_table': 'detalles_recepcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero_orden', models.CharField(db_index=True, max_length=50, verbose_name='número de orden')),
                ('fecha_orden', models.DateField(verbose_name='fecha de orden')),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True, verbose_name='fecha de entrega esperada')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('PARCIAL', 'Recibida Parcialmente'), ('RECIBIDA', 'Recibida Completamente'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='descuento')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'órdenes de compra',
                'db_table': 'ordenes_compra',
                'ordering': ['-fecha_orden', '-numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero_pago', models.CharField(db_index=True, max_length=50, verbose_name='número de pago')),
                ('fecha_pago', models.DateField(verbose_name='fecha de pago')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta de Crédito'), ('NOTA_CREDITO', 'Nota de Crédito')], max_length=20, verbose_name='forma de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('numero_documento', models.CharField(blank=True, help_text='Número de cheque, transferencia, etc.', max_length=100, verbose_name='número de documento')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='banco')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'pago a proveedor',
                'verbose_name_plural': 'pagos a proveedores',
                'db_table': 'pagos_proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('RUC', 'RUC'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], default='RUC', max_length=10, verbose_name='tipo de identificación')),
                ('identificacion', models.CharField(db_index=True, max_length=13, verbose_name='identificación')),
                ('razon_social', models.CharField(max_length=300, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, verbose_name='nombre comercial')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('celular', models.CharField(blank=True, max_length=50, verbose_name='celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('contacto_principal', models.CharField(blank=True, max_length=200, verbose_name='contacto principal')),
                ('dias_credito', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='días de crédito')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='límite de crédito')),
                ('cuenta_contable', models.CharField(blank=True, help_text='Cuenta contable de cuentas por pagar', max_length=50, verbose_name='cuenta contable')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero_recepcion', models.CharField(db_index=True, max_length=50, verbose_name='número de recepción')),
                ('fecha_recepcion', models.DateField(verbose_name='fecha de recepción')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=50, verbose_name='número de factura proveedor')),
                ('fecha_factura_proveedor', models.DateField(blank=True, null=True, verbose_name='fecha factura proveedor')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_compra', to='inventarios.bodega', verbose_name='bodega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_compra', to='empresas.empresa', verbose_name='empresa')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='proveedores.ordencompra', verbose_name='orden de compra')),
            ],
            options={
                'verbose_name': 'recepción de compra',
                'verbose_name_plural': 'recepciones de compra',
                'db_table': 'recepciones_compra',
                'ordering': ['-fecha_recepcion', '-numero_recepcion'],
            },
        ),
    ]
