# Generated by Django 4.2.27 on 2026-01-30 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventarios', '0002_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcioncompra',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='recibido por'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='cuenta_por_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='proveedores.cuentaporpagar', verbose_name='cuenta por pagar'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_proveedores', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='proveedores.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='bodega_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='inventarios.bodega', verbose_name='bodega destino'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='proveedores.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='detalle_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='proveedores.detalleordencompra', verbose_name='detalle de orden'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.recepcioncompra', verbose_name='recepción'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.ordencompra', verbose_name='orden de compra'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_compra', to='productos.producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='proveedores.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='recepcion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='proveedores.recepcioncompra', verbose_name='recepción'),
        ),
        migrations.AddIndex(
            model_name='recepcioncompra',
            index=models.Index(fields=['empresa', 'estado'], name='recepciones_empresa_7401b5_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcioncompra',
            index=models.Index(fields=['empresa', 'orden_compra'], name='recepciones_empresa_5f6531_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcioncompra',
            index=models.Index(fields=['fecha_recepcion'], name='recepciones_fecha_r_bc371d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recepcioncompra',
            unique_together={('empresa', 'numero_recepcion')},
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'activo'], name='proveedores_empresa_85c31d_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'identificacion'], name='proveedores_empresa_fd7a72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('empresa', 'identificacion')},
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['empresa', 'proveedor'], name='pagos_prove_empresa_27e161_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['empresa', 'cuenta_por_pagar'], name='pagos_prove_empresa_720318_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['fecha_pago'], name='pagos_prove_fecha_p_67b49a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagoproveedor',
            unique_together={('empresa', 'numero_pago')},
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'estado'], name='ordenes_com_empresa_e00f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'proveedor'], name='ordenes_com_empresa_3f26d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_orden'], name='ordenes_com_fecha_o_6951ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together={('empresa', 'numero_orden')},
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['empresa', 'estado'], name='cuentas_por_empresa_356a30_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['empresa', 'proveedor'], name='cuentas_por_empresa_3d5c02_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['fecha_vencimiento'], name='cuentas_por_fecha_v_10e65a_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['fecha_emision'], name='cuentas_por_fecha_e_a6d1ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentaporpagar',
            unique_together={('empresa', 'numero_cuenta')},
        ),
    ]
