# Generated by Django 4.2.27 on 2026-06-18 21:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_precio'),
        ('empresas', '0007_alter_empresa_password_certificado'),
        ('proveedores', '0003_pago_proveedor_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=60)),
                ('costo_referencia', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('dias_entrega', models.PositiveIntegerField(default=0)),
                ('es_preferido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_productos', to='empresas.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_catalogo', to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_catalogo', to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'proveedores_productos',
                'ordering': ['producto__nombre', '-es_preferido', 'proveedor__razon_social'],
                'indexes': [models.Index(fields=['empresa', 'producto', 'activo'], name='proveedores_empresa_cdcb07_idx'), models.Index(fields=['empresa', 'proveedor', 'activo'], name='proveedores_empresa_e5e273_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proveedorproducto',
            constraint=models.UniqueConstraint(fields=('empresa', 'proveedor', 'producto'), name='uniq_empresa_proveedor_producto'),
        ),
    ]
