# Generated by Django 4.2.27 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedorproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de caducidad'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=80, verbose_name='número de lote'),
        ),
        migrations.AddIndex(
            model_name='detallerecepcion',
            index=models.Index(fields=['numero_lote'], name='detalles_re_numero__018355_idx'),
        ),
        migrations.AddIndex(
            model_name='detallerecepcion',
            index=models.Index(fields=['fecha_caducidad'], name='detalles_re_fecha_c_ec186d_idx'),
        ),
    ]
