# Generated by Django 4.2.27 on 2026-09-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0005_detallerecepcion_lote_caducidad"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="detallerecepcion",
            new_name="detalles_re_numero__a9a968_idx",
            old_name="detalles_re_numero__018355_idx",
        ),
        migrations.RenameIndex(
            model_name="detallerecepcion",
            new_name="detalles_re_fecha_c_0c04e2_idx",
            old_name="detalles_re_fecha_c_ec186d_idx",
        ),
    ]
