# Generated by Django 4.2.27 on 2026-08-21 15:36

import apps.firmador.models
import apps.firmador.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0008_empresa_ruc_proveedor_facturacion_electronica'),
        ('firmas', '0014_solicitudfirmaelectronica_parish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmadorWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONA_NATURAL', 'Persona natural'), ('ORGANIZACION', 'Organización'), ('EMPRESA_ERP', 'Empresa ERP'), ('CLIENTE_FIRMA', 'Cliente de firma electrónica')], default='PERSONA_NATURAL', max_length=30, verbose_name='tipo')),
                ('nombre', models.CharField(max_length=180, verbose_name='nombre')),
                ('identificacion', models.CharField(blank=True, max_length=20, verbose_name='identificación')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('max_file_size_bytes', models.BigIntegerField(default=26214400, verbose_name='máximo por archivo')),
                ('max_storage_bytes', models.BigIntegerField(default=1073741824, verbose_name='cuota de almacenamiento')),
                ('monthly_signature_limit', models.PositiveIntegerField(default=100, verbose_name='firmas mensuales')),
                ('default_retention_days', models.PositiveIntegerField(default=30, verbose_name='retención predeterminada')),
                ('max_retention_days', models.PositiveIntegerField(default=180, verbose_name='retención máxima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmador_workspaces', to='empresas.empresa', verbose_name='empresa ERP')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmador_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='usuario propietario')),
                ('solicitud_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmador_workspaces', to='firmas.solicitudfirmaelectronica', verbose_name='solicitud de firma electrónica')),
            ],
            options={
                'verbose_name': 'workspace del firmador',
                'verbose_name_plural': 'workspaces del firmador',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmadorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, null=True, storage=apps.firmador.storage.FirmadorDocumentStorage(), upload_to=apps.firmador.models.firmador_upload_to, verbose_name='PDF original')),
                ('signed_file', models.FileField(blank=True, null=True, storage=apps.firmador.storage.FirmadorDocumentStorage(), upload_to=apps.firmador.models.firmador_upload_to, verbose_name='PDF firmado')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='archivo original')),
                ('signed_file_name', models.CharField(blank=True, max_length=255, verbose_name='archivo firmado')),
                ('original_size', models.BigIntegerField(default=0, verbose_name='tamaño original')),
                ('signed_size', models.BigIntegerField(default=0, verbose_name='tamaño firmado')),
                ('stored_bytes', models.BigIntegerField(default=0, verbose_name='bytes almacenados')),
                ('original_hash', models.CharField(blank=True, max_length=64, verbose_name='hash original')),
                ('signed_hash', models.CharField(blank=True, max_length=64, verbose_name='hash firmado')),
                ('keep_file', models.BooleanField(default=False, verbose_name='guardar archivo')),
                ('retention_days', models.PositiveIntegerField(default=0, verbose_name='días de retención')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('status', models.CharField(choices=[('FIRMADO', 'Firmado'), ('ERROR', 'Error'), ('EXPIRADO', 'Expirado'), ('ELIMINADO', 'Eliminado')], default='FIRMADO', max_length=20, verbose_name='estado')),
                ('certificado_origen', models.CharField(choices=[('TEMPORAL', 'Temporal'), ('EMPRESA', 'Certificado de empresa')], default='TEMPORAL', max_length=20, verbose_name='origen certificado')),
                ('reason', models.CharField(blank=True, max_length=180, verbose_name='razón')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='ubicación')),
                ('visible_signature', models.BooleanField(default=False, verbose_name='firma visible')),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_firmador', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='firmador.firmadorworkspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'documento firmado',
                'verbose_name_plural': 'documentos firmados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='firmadorworkspace',
            index=models.Index(fields=['owner_user', 'activo'], name='firmador_fi_owner_u_c705f0_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadorworkspace',
            index=models.Index(fields=['empresa', 'activo'], name='firmador_fi_empresa_fc82ab_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadorworkspace',
            index=models.Index(fields=['solicitud_firma'], name='firmador_fi_solicit_ae8ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadordocumento',
            index=models.Index(fields=['workspace', 'status'], name='firmador_fi_workspa_e0ece8_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadordocumento',
            index=models.Index(fields=['workspace', 'expires_at'], name='firmador_fi_workspa_4a1999_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadordocumento',
            index=models.Index(fields=['user', 'created_at'], name='firmador_fi_user_id_1e4bb9_idx'),
        ),
    ]
