# Generated by Django 4.2.27 on 2026-08-21 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firmador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmadordocumento',
            name='certificado_origen',
            field=models.CharField(choices=[('TEMPORAL', 'Temporal'), ('GUARDADO', 'Guardado'), ('EMPRESA', 'Certificado de empresa')], default='TEMPORAL', max_length=20, verbose_name='origen certificado'),
        ),
        migrations.CreateModel(
            name='FirmadorCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120, verbose_name='alias')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='archivo')),
                ('encrypted_content', models.BinaryField(verbose_name='contenido cifrado')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='tamaÃ±o')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='huella')),
                ('subject', models.TextField(blank=True, verbose_name='sujeto')),
                ('issuer', models.TextField(blank=True, verbose_name='emisor')),
                ('expires_at', models.DateTimeField(verbose_name='expira')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizaciÃ³n')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_firmador', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='firmador.firmadorworkspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'certificado del firmador',
                'verbose_name_plural': 'certificados del firmador',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='firmadordocumento',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='firmador.firmadorcertificado', verbose_name='certificado'),
        ),
        migrations.AddIndex(
            model_name='firmadorcertificado',
            index=models.Index(fields=['workspace', 'active'], name='firmador_fi_workspa_da3f25_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadorcertificado',
            index=models.Index(fields=['expires_at'], name='firmador_fi_expires_af324b_idx'),
        ),
        migrations.AddConstraint(
            model_name='firmadorcertificado',
            constraint=models.UniqueConstraint(condition=django.db.models.Q(active=True), fields=('workspace', 'fingerprint'), name='uniq_firmador_certificado_activo'),
        ),
    ]
