# Generated by Codex on 2026-08-21

import apps.firmador.models
import apps.firmador.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmador', '0003_firmadordocumento_signature_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmadordocumento',
            name='original_file',
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=apps.firmador.storage.FirmadorDocumentStorage(),
                upload_to=apps.firmador.models.firmador_upload_to,
                verbose_name='PDF original',
            ),
        ),
        migrations.AlterField(
            model_name='firmadordocumento',
            name='signed_file',
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=apps.firmador.storage.FirmadorDocumentStorage(),
                upload_to=apps.firmador.models.firmador_upload_to,
                verbose_name='PDF firmado',
            ),
        ),
    ]
