# Generated by Codex on 2026-08-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firmador', '0004_alter_firmadordocumento_file_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmadorConsentimientoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_terms', models.BooleanField(default=True, verbose_name='acepto terminos')),
                ('accepted_privacy', models.BooleanField(default=True, verbose_name='acepto privacidad')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de aceptacion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='direccion IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('terms_version', models.CharField(max_length=40, verbose_name='version de terminos')),
                ('privacy_version', models.CharField(max_length=40, verbose_name='version de privacidad')),
                ('source', models.CharField(choices=[('firmador_registro', 'Registro del firmador'), ('admin', 'Administracion'), ('otro', 'Otro')], default='firmador_registro', max_length=40, verbose_name='origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_firmador', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_legales', to='firmador.firmadorworkspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'consentimiento legal del firmador',
                'verbose_name_plural': 'consentimientos legales del firmador',
                'db_table': 'firmador_legal_consents',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='firmadorconsentimientolegal',
            index=models.Index(fields=['user', 'accepted_at'], name='firmador_le_user_id_e328ac_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadorconsentimientolegal',
            index=models.Index(fields=['workspace', 'accepted_at'], name='firmador_le_workspa_3ba0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadorconsentimientolegal',
            index=models.Index(fields=['terms_version', 'privacy_version'], name='firmador_le_terms_v_fb5749_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadorconsentimientolegal',
            index=models.Index(fields=['source'], name='firmador_le_source_83b467_idx'),
        ),
    ]
