# Generated by Django 4.2.27 on 2026-09-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firmador", "0006_firmadorworkspace_is_primary"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="firmadorworkspace",
            new_name="firmador_fi_owner_u_b80a16_idx",
            old_name="firmador_fi_owner__f7c4d4_idx",
        ),
    ]
