# Generated by Django 4.2.27 on 2026-01-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('tipo', models.CharField(choices=[('BASICO', 'Básico'), ('PROFESIONAL', 'Profesional'), ('EMPRESARIAL', 'Empresarial'), ('ILIMITADO', 'Ilimitado')], max_length=20, verbose_name='tipo')),
                ('periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20, verbose_name='periodo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('facturas_mensuales', models.IntegerField(help_text='Número de facturas permitidas por mes (0 = ilimitado)', verbose_name='facturas mensuales')),
                ('usuarios_permitidos', models.IntegerField(help_text='Número máximo de usuarios (0 = ilimitado)', verbose_name='usuarios permitidos')),
                ('empresas_permitidas', models.IntegerField(default=1, help_text='Número de empresas que puede administrar', verbose_name='empresas permitidas')),
                ('soporte_prioritario', models.BooleanField(default=False, verbose_name='soporte prioritario')),
                ('api_access', models.BooleanField(default=False, verbose_name='acceso API')),
                ('reportes_avanzados', models.BooleanField(default=False, verbose_name='reportes avanzados')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
            ],
            options={
                'verbose_name': 'plan de suscripción',
                'verbose_name_plural': 'planes de suscripción',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='fecha de fin')),
                ('fecha_proximo_pago', models.DateTimeField(blank=True, null=True, verbose_name='fecha próximo pago')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('SUSPENDIDA', 'Suspendida'), ('PRUEBA', 'Período de Prueba')], default='ACTIVA', max_length=20, verbose_name='estado')),
                ('auto_renovar', models.BooleanField(default=True, verbose_name='auto renovar')),
                ('facturas_emitidas_mes_actual', models.IntegerField(default=0, verbose_name='facturas emitidas este mes')),
                ('ultimo_reset_contador', models.DateField(auto_now_add=True, verbose_name='último reset contador')),
                ('notificado_por_vencer', models.BooleanField(default=False, verbose_name='notificado por vencer')),
                ('dias_notificacion_vencimiento', models.IntegerField(default=7, help_text='Días antes del vencimiento para enviar notificación', verbose_name='días para notificar vencimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='empresas.empresa', verbose_name='empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plansuscripcion', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('tipo', models.CharField(choices=[('NUEVA', 'Nueva Suscripción'), ('RENOVACION', 'Renovación'), ('UPGRADE', 'Upgrade de Plan'), ('DOWNGRADE', 'Downgrade de Plan')], max_length=20, verbose_name='tipo')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('PAYPAL', 'PayPal'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20, verbose_name='método de pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='referencia')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/', verbose_name='comprobante')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de aprobación')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripciones.suscripcion', verbose_name='suscripción')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['empresa', 'estado'], name='suscripcion_empresa_243fde_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['fecha_fin'], name='suscripcion_fecha_f_0ad475_idx'),
        ),
    ]
