# Generated by Django 4.2.27 on 2026-03-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plansuscripcion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("FREE", "Gratuito"),
                    ("BASICO", "Básico"),
                    ("PROFESIONAL", "Profesional"),
                    ("EMPRESARIAL", "Empresarial"),
                    ("ILIMITADO", "Ilimitado"),
                ],
                max_length=20,
                verbose_name="tipo",
            ),
        ),
    ]
