# Generated by Django 4.2.27 on 2026-03-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0002_add_free_plan_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuloPermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("facturacion", "Facturación"),
                            ("retenciones", "Retenciones"),
                            ("guias_remision", "Guías de Remisión"),
                            ("notas_debito", "Notas de Débito"),
                            ("notas_credito", "Notas de Crédito"),
                            ("cartera", "Cartera por Cobrar"),
                            ("declaraciones", "Declaraciones SRI"),
                            ("cotizaciones", "Cotizaciones"),
                            ("contabilidad", "Contabilidad"),
                            ("bancos", "Bancos"),
                            ("nomina", "Nómina"),
                            ("ventas", "Ventas"),
                            ("pedidos", "Mesas / Pedidos"),
                            ("clientes", "Clientes"),
                            ("productos", "Productos"),
                            ("proveedores", "Proveedores"),
                            ("inventarios", "Inventarios"),
                            ("reportes", "Reportes"),
                            ("configuracion", "Configuración"),
                            ("usuarios", "Usuarios"),
                            ("pos", "Punto de Venta"),
                        ],
                        max_length=50,
                        verbose_name="módulo",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos_permitidos",
                        to="suscripciones.plansuscripcion",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "permiso de módulo",
                "verbose_name_plural": "permisos de módulos",
                "ordering": ["plan", "modulo"],
                "unique_together": {("plan", "modulo")},
            },
        ),
    ]
