# Generated by Django 4.2.27 on 2026-06-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_precio'),
        ('suscripciones', '0009_firmas_superadmin_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='producto_erp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_suscripcion', to='productos.producto', verbose_name='producto ERP'),
        ),
    ]
