# Generated by Django 4.2.27 on 2026-03-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="codigo_verificacion",
            field=models.CharField(
                blank=True, max_length=8, verbose_name="código de verificación"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="codigo_verificacion_expira",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expiración código"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="email_verificado",
            field=models.BooleanField(default=False, verbose_name="email verificado"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="intentos_reenvio",
            field=models.IntegerField(default=0, verbose_name="intentos de reenvío"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="ultimo_reenvio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="último reenvío"
            ),
        ),
    ]
