# Generated by Django 4.2.27 on 2026-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_codigo_verificacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_password",
            field=models.BooleanField(
                default=False, verbose_name="debe cambiar contraseña"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="password_temporal",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="contraseña temporal"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="password_temporal_expira",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expiración contraseña temporal"
            ),
        ),
    ]
