# Generated by Django 4.2.27 on 2026-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_add_password_reset_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMIN_EMPRESA', 'Administrador de Empresa'), ('CONTADOR', 'Contador'), ('VENDEDOR', 'Vendedor'), ('CONSULTOR', 'Consultor'), ('FIRMADOR', 'Usuario Firmador')], default='VENDEDOR', max_length=20, verbose_name='rol'),
        ),
    ]
