# Generated by Django 4.2.27 on 2026-03-10 06:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0003_empresa_onboarding_completado"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100, verbose_name="banco")),
                (
                    "numero_cuenta",
                    models.CharField(max_length=50, verbose_name="número de cuenta"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CORRIENTE", "Cuenta Corriente"),
                            ("AHORROS", "Cuenta de Ahorros"),
                            ("CAJA", "Caja"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="moneda"
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="saldo inicial",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_bancarias",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta bancaria",
                "verbose_name_plural": "cuentas bancarias",
                "ordering": ["banco", "numero_cuenta"],
                "unique_together": {("empresa", "numero_cuenta")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEPOSITO", "Depósito"),
                            ("RETIRO", "Retiro"),
                            ("TRANSFERENCIA_ENTRADA", "Transferencia Entrada"),
                            ("TRANSFERENCIA_SALIDA", "Transferencia Salida"),
                            ("NOTA_CREDITO", "Nota de Crédito Banco"),
                            ("NOTA_DEBITO", "Nota de Débito Banco"),
                            ("CHEQUE", "Cheque Emitido"),
                            ("PAGO", "Pago"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=300, verbose_name="descripción"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Nro. cheque, transf., factura, etc.",
                        max_length=100,
                        verbose_name="referencia",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="monto"
                    ),
                ),
                (
                    "conciliado",
                    models.BooleanField(default=False, verbose_name="conciliado"),
                ),
                (
                    "beneficiario",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="beneficiario/origen"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="bancos.cuentabancaria",
                        verbose_name="cuenta bancaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento bancario",
                "verbose_name_plural": "movimientos bancarios",
                "ordering": ["-fecha", "-id"],
            },
        ),
    ]
