# Generated by Django 4.2.27 on 2026-09-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documentos_recibidos", "0001_initial"),
        ("proveedores", "0005_detallerecepcion_lote_caducidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentorecibidosri",
            name="cuenta_por_pagar",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="documento_recibido_sri", to="proveedores.cuentaporpagar", verbose_name="cuenta por pagar"),
        ),
        migrations.AddField(
            model_name="documentorecibidosri",
            name="fecha_conversion",
            field=models.DateTimeField(blank=True, null=True, verbose_name="fecha de conversion"),
        ),
        migrations.AddField(
            model_name="documentorecibidosri",
            name="proveedor",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="documentos_recibidos_sri", to="proveedores.proveedor", verbose_name="proveedor"),
        ),
        migrations.RenameIndex(
            model_name="documentorecibidosri",
            new_name="documentos__empresa_a76764_idx",
            old_name="documentos__empresa_d7c575_idx",
        ),
        migrations.RenameIndex(
            model_name="documentorecibidosri",
            new_name="documentos__empresa_fdca14_idx",
            old_name="documentos__empresa_c5bfcd_idx",
        ),
        migrations.RenameIndex(
            model_name="documentorecibidosri",
            new_name="documentos__empresa_76bb93_idx",
            old_name="documentos__empresa_96a413_idx",
        ),
        migrations.RenameIndex(
            model_name="documentorecibidosri",
            new_name="documentos__empresa_795562_idx",
            old_name="documentos__empresa_81df9e_idx",
        ),
    ]
