# Generated by Django 4.2.27 on 2026-01-30 04:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0001_initial'),
        ('inventarios', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha apertura')),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monto apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='fecha cierre')),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto cierre')),
                ('monto_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto esperado')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='diferencia')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'apertura de caja',
                'verbose_name_plural': 'aperturas de caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('impresora_termica', models.CharField(blank=True, max_length=200, verbose_name='impresora térmica')),
                ('ancho_papel', models.IntegerField(default=80, verbose_name='ancho papel (mm)')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='inventarios.bodega', verbose_name='bodega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'caja',
                'verbose_name_plural': 'cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(max_length=20, verbose_name='número de venta')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('tipo_venta', models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('CREDITO', 'Crédito'), ('PEDIDO', 'Pedido')], default='MOSTRADOR', max_length=20, verbose_name='tipo de venta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='descuento')),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal 0%')),
                ('subtotal_12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal 12%')),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal 15%')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('genera_factura', models.BooleanField(default=False, verbose_name='genera factura electrónica')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha venta')),
                ('sincronizada', models.BooleanField(default=False, verbose_name='sincronizada')),
                ('fecha_sincronizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha sincronización')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('apertura_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.aperturacaja', verbose_name='apertura caja')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.caja', verbose_name='caja')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente', verbose_name='cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='empresas.empresa', verbose_name='empresa')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='facturacion.factura', verbose_name='factura electrónica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito')], max_length=20, verbose_name='forma de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='referencia')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha pago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'pago de venta',
                'verbose_name_plural': 'pagos de venta',
                'ordering': ['fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('concepto', models.CharField(max_length=200, verbose_name='concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha movimiento')),
                ('apertura_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ventas.aperturacaja', verbose_name='apertura caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'movimiento de caja',
                'verbose_name_plural': 'movimientos de caja',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12, verbose_name='costo unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto', verbose_name='producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='ventas.caja', verbose_name='caja'),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'fecha_venta'], name='ventas_vent_empresa_8b8867_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['uuid'], name='ventas_vent_uuid_fe39ac_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_venta'], name='ventas_vent_numero__48e038_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sincronizada'], name='ventas_vent_sincron_e6b77c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caja',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['caja', 'estado'], name='ventas_aper_caja_id_2d2209_idx'),
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['fecha_apertura'], name='ventas_aper_fecha_a_25617e_idx'),
        ),
    ]
