# Generated by Django 4.2.27 on 2026-06-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_initial'),
        ('proveedores', '0004_proveedorproducto_and_more'),
        ('ventas', '0003_pago_cuenta_bancaria_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_venta', to='inventarios.bodega', verbose_name='bodega de salida'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_venta', to='proveedores.proveedor', verbose_name='proveedor de origen'),
        ),
    ]
