# Generated by Django 4.2.27 on 2026-06-23 03:38

from django.db import migrations, models


def marcar_pagos_con_movimiento_como_pagados(apps, schema_editor):
    PagoVenta = apps.get_model('ventas', 'PagoVenta')
    PagoVenta.objects.filter(movimiento_bancario__isnull=False).update(estado_pago='PAGADO')


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detalleventa_bodega_detalleventa_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20, verbose_name='estado pago'),
        ),
        migrations.RunPython(marcar_pagos_con_movimiento_como_pagados, migrations.RunPython.noop),
    ]
